### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by alittlecup** [luffyjet/WebViewJavaScriptBridge#3]
之前谢了好多，因为失误都没有了（手动捂脸）
1.关于在handle方法中BridgeInterface存在的必要性，因为它的作用就是将handler注入到activity中，然后回去回调。但是有很多其实是不需要回调的。
2.如果不用BridgeInterface，那么handle方法中需要上下文Context对象吗？因为从整个的交互来看，只有在获取本地数据的时候才需要Context，但是本地数据应该是客户本身去获取的，是，提供上下文会更方便。
3.其实根本的问题是在handle方法中怎么做才能让用户更好的注入结果，并没有想到一个很好的方式。

是否可以考虑使用最干净的方式就是只有data和function?用户的数据获取由其自己去实现，这样同样会有一个问题就是在Handler中，数据的注入并不方便，纠结啊。

**Comment by alittlecup** [comment]
为什么是#3？

**Comment by luffyjet** [comment]
@alittlecup 

1.  使用了模块（插件）化管理的方式后，为了处理onActivityResult ，onRequestPermissionResult（我还没放进去）等等这类异步的需求，就有了BridgeInterface，我觉得大多数场景都会用到 。

2.  如果用了模块化的方式编写，不用BridgeInterface ，不好获得Context。很多功能无法实现。

3.  BridgeInterface 的方式来自Cordova，是一个比较好的方式。具体可以去看看[cordova-android](https://github.com/apache/cordova-android)的源码。

最干净的方式我这个也能用，直接在WebActivity里调用 mBridge.registerHandler 和 mBridge.callHandler即可，这样Context问题也不用担心。 

不过后面业务一复杂，比如要打造一个类似微信的jssdk，提供大量原生能力给js调用的时候，大量的业务代码就都写在 activity里面，造成不好管理，不好扩展，多团队开发不方便，代码不优雅等问题。所以将每一种原生提供的能力都独立成插件是个不错的解决方式，我这个还不完全，具体可以参考 cordova-cli 、 cordova-plugins的做法。

**Comment by luffyjet** [comment]
之前有两个 pull。所以是 3  @alittlecup

**Comment by alittlecup** [comment]
谢谢，我再学习学习
